spring:
  application:
    name: api-contract
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          billing-data-collector:
            authorization-grant-type: client_credentials
            provider: billing-data-collector

integration:
  billing-data-collector:
    connect-timeout: 5
    read-timeout: 15

dept44:
  models:
    api:
      paging:
        max:
          limit: 100

openapi:
  name: ${spring.application.name}
  title: Contracts
  version: '@project.version@'
